name: Build and upload bindings
on:
  workflow_dispatch:
  workflow_call:

inputs:
  cache_id:
    required: true
  nar_secret:
    required: true
  gcp_secret:
    required: true

runs:
  using: "composite"
  steps:
    - name: Build
      uses: ./.github/actions/build
      with:
          cache_id: ${{ inputs.cache_id }}
          nar_secret: ${{ inputs.nar_secret }}
          gcp_secret: ${{ inputs.gcp_secret }}

    - name: generate tar
      shell: bash
      run: |
        set -Eeu
        ./pin.sh
        nix build o1js#bindings-tar --out-link bindings.tar.gz
    - name: Upload bindings
      uses: actions/upload-artifact@v4
      with:
        name: bindings.tar.gz
        path: bindings.tar.gz
