name: Build and upload bindings
on:
  workflow_dispatch:
  workflow_call:

runs:
  using: "composite"
  steps:
    - name: Build
      uses: ./.github/actions/build
    - name: generate tar
      run: |
        set -Eeu
        ./pin.sh
        nix build o1js#bindings-tar --out-link bindings.tar.gz
    - name: Upload bindings
      uses: actions/upload-artifact@v4
      with:
        name: bindings.tar.gz
        path: bindings.tar.gz
