// generated by mina-signer@3.0.7 (berkeley, o1js v2.9.0) on 2026-06-17
//
// inputs and signatures produced by calling the real mina-signer@3.0.7 API with a
// fixed private key. zkapp1 omits `update.appState` and zkapp2 omits
// `setVerificationKey.txnVersion` in their stored inputs; the signatures are
// computed from the defaulted commands ([null x 8] appState, txnVersion '3').
//
// provenance is reproducible: ./verify-berkeley-vectors.mjs re-signs every vector
// here with the real mina-signer@3.0.7 and asserts it matches (proves these came
// from @3.0.7, not from this branch — i.e. berkeley.unit-test.ts is not circular).

export { berkeleyVectors };

let berkeleyVectors = {
  "keypair": {
    "privateKey": "EKFKgDtU3rcuFTVSEpmpXSkukjmX4cKefYREi6Sdsk7E7wsT7KRw",
    "publicKey": "B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg"
  },
  "network": "testnet",
  "payment": {
    "input": {
      "to": "B62qrcFstkpqXww1EkSGrqMCwCNho86kuqBd4FrAAUsPxNKdiPzAUsy",
      "from": "B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg",
      "fee": "3",
      "nonce": "200",
      "validUntil": "10000",
      "memo": "this is a memo",
      "amount": "42"
    },
    "output": {
      "signature": {
        "field": "3925887987173883783388058255268083382298769764463609405200521482763932632383",
        "scalar": "445615701481226398197189554290689546503290167815530435382795701939759548136"
      },
      "publicKey": "B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg",
      "data": {
        "to": "B62qrcFstkpqXww1EkSGrqMCwCNho86kuqBd4FrAAUsPxNKdiPzAUsy",
        "from": "B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg",
        "fee": "3",
        "amount": "42",
        "nonce": "200",
        "memo": "this is a memo",
        "validUntil": "10000"
      }
    }
  },
  "stakeDelegation": {
    "input": {
      "to": "B62qkfHpLpELqpMK6ZvUTJ5wRqKDRF3UHyJ4Kv3FU79Sgs4qpBnx5RR",
      "from": "B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg",
      "fee": "3",
      "nonce": "10",
      "validUntil": "4000",
      "memo": "more delegates, more fun"
    },
    "output": {
      "signature": {
        "field": "18603328765572408555868399359399411973012220541556204196884026585115374044583",
        "scalar": "17076342019359061119005549736934690084415105419939473687106079907606137611470"
      },
      "publicKey": "B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg",
      "data": {
        "to": "B62qkfHpLpELqpMK6ZvUTJ5wRqKDRF3UHyJ4Kv3FU79Sgs4qpBnx5RR",
        "from": "B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg",
        "fee": "3",
        "nonce": "10",
        "memo": "more delegates, more fun",
        "validUntil": "4000"
      }
    }
  },
  "message": {
    "input": "this is a test",
    "output": {
      "signature": {
        "field": "11583775536286847540414661987230057163492736306749717851628536966882998258109",
        "scalar": "14787360096063782022566783796923142259879388947509616216546009448340181956495"
      },
      "publicKey": "B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg",
      "data": "this is a test"
    }
  },
  "fields": {
    "input": [
      "1",
      "2",
      "3"
    ],
    "output": {
      "signature": "7mXHor65E5LW5xPJteG3DWzBkV4H63FFvvohs8hnViL73WpyZ7VN5tSP1ZUJ7kGN7iGR4uMxjAw8hLm2KZArakChE8yHuHFA",
      "publicKey": "B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg",
      "data": [
        "1",
        "2",
        "3"
      ]
    }
  },
  "nullifier": {
    "input": [
      "1",
      "2"
    ],
    "output": {
      "publicKey": {
        "x": "22536877747820698688010660184495467853785925552441222123266613953322243475471",
        "y": "17959090007449995703063422061813262153384931532365104340746472887908551982252"
      },
      "private": {
        "c": "6684536487749937492143964673674434814351532940370958060270316104707166489237",
        "g_r": {
          "x": "4072772576855985536692362160969536396593668095077074486339088634159609396452",
          "y": "21027849040353338624309442193345266727905564643094971539822807661108670287175"
        },
        "h_m_pk_r": {
          "x": "27407722077631477305929187875449534361533669316192718468460800229037105961419",
          "y": "14097552204004523541649392482060157548678469483837372678835030130168814698909"
        }
      },
      "public": {
        "nullifier": {
          "x": "856560859766907084330521253591601912916120163932549325571430181628307163090",
          "y": "1211521076057019327166683598894727665153724596681070468875972889505985194989"
        },
        "s": "4429549838993967787511387737173139406507729613500941912958519135511622111100"
      }
    }
  },
  "zkapp1": {
    "input": {
      "zkappCommand": {
        "accountUpdates": [
          {
            "body": {
              "publicKey": "B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg",
              "tokenId": "wSHV2S4qX9jFsLjQo8r1BsMLH2ZRKsZx6EJd1sbozGPieEC4Jf",
              "update": {
                "delegate": null,
                "verificationKey": null,
                "permissions": null,
                "zkappUri": null,
                "tokenSymbol": null,
                "timing": null,
                "votingFor": null
              },
              "balanceChange": {
                "magnitude": "0",
                "sgn": "Positive"
              },
              "incrementNonce": false,
              "events": [],
              "actions": [],
              "callData": "0",
              "callDepth": 0,
              "preconditions": {
                "network": {
                  "snarkedLedgerHash": null,
                  "blockchainLength": null,
                  "minWindowDensity": null,
                  "totalCurrency": null,
                  "globalSlotSinceGenesis": null,
                  "stakingEpochData": {
                    "ledger": {
                      "hash": null,
                      "totalCurrency": null
                    },
                    "seed": null,
                    "startCheckpoint": null,
                    "lockCheckpoint": null,
                    "epochLength": null
                  },
                  "nextEpochData": {
                    "ledger": {
                      "hash": null,
                      "totalCurrency": null
                    },
                    "seed": null,
                    "startCheckpoint": null,
                    "lockCheckpoint": null,
                    "epochLength": null
                  }
                },
                "account": {
                  "balance": null,
                  "nonce": null,
                  "receiptChainHash": null,
                  "delegate": null,
                  "state": [
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                  ],
                  "actionState": null,
                  "provedState": null,
                  "isNew": null
                },
                "validWhile": null
              },
              "useFullCommitment": false,
              "implicitAccountCreationFee": false,
              "mayUseToken": {
                "parentsOwnToken": false,
                "inheritFromParent": false
              },
              "authorizationKind": {
                "isSigned": false,
                "isProved": false,
                "verificationKeyHash": "3392518251768960475377392625298437850623664973002200885669375116181514017494"
              }
            },
            "authorization": {
              "proof": null,
              "signature": null
            }
          }
        ],
        "memo": "E4YM2vTHhWEg66xpj52JErHUBU4pZ1yageL4TVDDpTTSsv8mK6YaH"
      },
      "feePayer": {
        "feePayer": "B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg",
        "fee": "1",
        "nonce": "0",
        "memo": "",
        "validUntil": "100"
      }
    },
    "output": {
      "signature": "7mXNaSNgF5CdHtdsgPjToSstMom7UDnuwKaoF9yScjqmpjDYoeRueuNoPDUqf3rZUjb1dD8Ruy3xXLS1YDBAj6ZUb3HCVFtX",
      "publicKey": "B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg",
      "data": {
        "zkappCommand": {
          "feePayer": {
            "body": {
              "publicKey": "B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg",
              "fee": "1",
              "validUntil": "100",
              "nonce": "0"
            },
            "authorization": "7mXNaSNgF5CdHtdsgPjToSstMom7UDnuwKaoF9yScjqmpjDYoeRueuNoPDUqf3rZUjb1dD8Ruy3xXLS1YDBAj6ZUb3HCVFtX"
          },
          "accountUpdates": [
            {
              "body": {
                "publicKey": "B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg",
                "tokenId": "wSHV2S4qX9jFsLjQo8r1BsMLH2ZRKsZx6EJd1sbozGPieEC4Jf",
                "update": {
                  "appState": [
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                  ],
                  "delegate": null,
                  "verificationKey": null,
                  "permissions": null,
                  "zkappUri": null,
                  "tokenSymbol": null,
                  "timing": null,
                  "votingFor": null
                },
                "balanceChange": {
                  "magnitude": "0",
                  "sgn": "Positive"
                },
                "incrementNonce": false,
                "events": [],
                "actions": [],
                "callData": "0",
                "callDepth": 0,
                "preconditions": {
                  "network": {
                    "snarkedLedgerHash": null,
                    "blockchainLength": null,
                    "minWindowDensity": null,
                    "totalCurrency": null,
                    "globalSlotSinceGenesis": null,
                    "stakingEpochData": {
                      "ledger": {
                        "hash": null,
                        "totalCurrency": null
                      },
                      "seed": null,
                      "startCheckpoint": null,
                      "lockCheckpoint": null,
                      "epochLength": null
                    },
                    "nextEpochData": {
                      "ledger": {
                        "hash": null,
                        "totalCurrency": null
                      },
                      "seed": null,
                      "startCheckpoint": null,
                      "lockCheckpoint": null,
                      "epochLength": null
                    }
                  },
                  "account": {
                    "balance": null,
                    "nonce": null,
                    "receiptChainHash": null,
                    "delegate": null,
                    "state": [
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null
                    ],
                    "actionState": null,
                    "provedState": null,
                    "isNew": null
                  },
                  "validWhile": null
                },
                "useFullCommitment": false,
                "implicitAccountCreationFee": false,
                "mayUseToken": {
                  "parentsOwnToken": false,
                  "inheritFromParent": false
                },
                "authorizationKind": {
                  "isSigned": false,
                  "isProved": false,
                  "verificationKeyHash": "3392518251768960475377392625298437850623664973002200885669375116181514017494"
                }
              },
              "authorization": {
                "proof": null,
                "signature": null
              }
            }
          ],
          "memo": "E4YM2vTHhWEg66xpj52JErHUBU4pZ1yageL4TVDDpTTSsv8mK6YaH"
        },
        "feePayer": {
          "feePayer": "B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg",
          "fee": "1",
          "nonce": "0",
          "memo": "",
          "validUntil": "100"
        }
      }
    }
  },
  "zkapp2": {
    "input": {
      "zkappCommand": {
        "accountUpdates": [
          {
            "body": {
              "publicKey": "B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg",
              "tokenId": "wSHV2S4qX9jFsLjQo8r1BsMLH2ZRKsZx6EJd1sbozGPieEC4Jf",
              "update": {
                "appState": [
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null,
                  null
                ],
                "delegate": null,
                "verificationKey": null,
                "permissions": {
                  "editState": "Proof",
                  "access": "None",
                  "send": "Signature",
                  "receive": "None",
                  "setDelegate": "Signature",
                  "setPermissions": "Signature",
                  "setVerificationKey": {
                    "auth": "Signature"
                  },
                  "setZkappUri": "Signature",
                  "editActionState": "Proof",
                  "setTokenSymbol": "Signature",
                  "incrementNonce": "Signature",
                  "setVotingFor": "Signature",
                  "setTiming": "Signature"
                },
                "zkappUri": null,
                "tokenSymbol": null,
                "timing": null,
                "votingFor": null
              },
              "balanceChange": {
                "magnitude": "0",
                "sgn": "Positive"
              },
              "incrementNonce": false,
              "events": [],
              "actions": [],
              "callData": "0",
              "callDepth": 0,
              "preconditions": {
                "network": {
                  "snarkedLedgerHash": null,
                  "blockchainLength": null,
                  "minWindowDensity": null,
                  "totalCurrency": null,
                  "globalSlotSinceGenesis": null,
                  "stakingEpochData": {
                    "ledger": {
                      "hash": null,
                      "totalCurrency": null
                    },
                    "seed": null,
                    "startCheckpoint": null,
                    "lockCheckpoint": null,
                    "epochLength": null
                  },
                  "nextEpochData": {
                    "ledger": {
                      "hash": null,
                      "totalCurrency": null
                    },
                    "seed": null,
                    "startCheckpoint": null,
                    "lockCheckpoint": null,
                    "epochLength": null
                  }
                },
                "account": {
                  "balance": null,
                  "nonce": null,
                  "receiptChainHash": null,
                  "delegate": null,
                  "state": [
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                  ],
                  "actionState": null,
                  "provedState": null,
                  "isNew": null
                },
                "validWhile": null
              },
              "useFullCommitment": false,
              "implicitAccountCreationFee": false,
              "mayUseToken": {
                "parentsOwnToken": false,
                "inheritFromParent": false
              },
              "authorizationKind": {
                "isSigned": false,
                "isProved": false,
                "verificationKeyHash": "3392518251768960475377392625298437850623664973002200885669375116181514017494"
              }
            },
            "authorization": {
              "proof": null,
              "signature": null
            }
          }
        ],
        "memo": "E4YM2vTHhWEg66xpj52JErHUBU4pZ1yageL4TVDDpTTSsv8mK6YaH"
      },
      "feePayer": {
        "feePayer": "B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg",
        "fee": "1",
        "nonce": "1",
        "memo": "",
        "validUntil": "200"
      }
    },
    "output": {
      "signature": "7mXRqhguXzQ1hrmFTMAmGRCUNrywNKsYaheHyS1LrrCmXUoeLF4aodQZPQi1TQgYXvfeZbWBchMUZKDZfDJpMn85FyzymTg2",
      "publicKey": "B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg",
      "data": {
        "zkappCommand": {
          "feePayer": {
            "body": {
              "publicKey": "B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg",
              "fee": "1",
              "validUntil": "200",
              "nonce": "1"
            },
            "authorization": "7mXRqhguXzQ1hrmFTMAmGRCUNrywNKsYaheHyS1LrrCmXUoeLF4aodQZPQi1TQgYXvfeZbWBchMUZKDZfDJpMn85FyzymTg2"
          },
          "accountUpdates": [
            {
              "body": {
                "publicKey": "B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg",
                "tokenId": "wSHV2S4qX9jFsLjQo8r1BsMLH2ZRKsZx6EJd1sbozGPieEC4Jf",
                "update": {
                  "appState": [
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                  ],
                  "delegate": null,
                  "verificationKey": null,
                  "permissions": {
                    "editState": "Proof",
                    "access": "None",
                    "send": "Signature",
                    "receive": "None",
                    "setDelegate": "Signature",
                    "setPermissions": "Signature",
                    "setVerificationKey": {
                      "auth": "Signature",
                      "txnVersion": "3"
                    },
                    "setZkappUri": "Signature",
                    "editActionState": "Proof",
                    "setTokenSymbol": "Signature",
                    "incrementNonce": "Signature",
                    "setVotingFor": "Signature",
                    "setTiming": "Signature"
                  },
                  "zkappUri": null,
                  "tokenSymbol": null,
                  "timing": null,
                  "votingFor": null
                },
                "balanceChange": {
                  "magnitude": "0",
                  "sgn": "Positive"
                },
                "incrementNonce": false,
                "events": [],
                "actions": [],
                "callData": "0",
                "callDepth": 0,
                "preconditions": {
                  "network": {
                    "snarkedLedgerHash": null,
                    "blockchainLength": null,
                    "minWindowDensity": null,
                    "totalCurrency": null,
                    "globalSlotSinceGenesis": null,
                    "stakingEpochData": {
                      "ledger": {
                        "hash": null,
                        "totalCurrency": null
                      },
                      "seed": null,
                      "startCheckpoint": null,
                      "lockCheckpoint": null,
                      "epochLength": null
                    },
                    "nextEpochData": {
                      "ledger": {
                        "hash": null,
                        "totalCurrency": null
                      },
                      "seed": null,
                      "startCheckpoint": null,
                      "lockCheckpoint": null,
                      "epochLength": null
                    }
                  },
                  "account": {
                    "balance": null,
                    "nonce": null,
                    "receiptChainHash": null,
                    "delegate": null,
                    "state": [
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null
                    ],
                    "actionState": null,
                    "provedState": null,
                    "isNew": null
                  },
                  "validWhile": null
                },
                "useFullCommitment": false,
                "implicitAccountCreationFee": false,
                "mayUseToken": {
                  "parentsOwnToken": false,
                  "inheritFromParent": false
                },
                "authorizationKind": {
                  "isSigned": false,
                  "isProved": false,
                  "verificationKeyHash": "3392518251768960475377392625298437850623664973002200885669375116181514017494"
                }
              },
              "authorization": {
                "proof": null,
                "signature": null
              }
            }
          ],
          "memo": "E4YM2vTHhWEg66xpj52JErHUBU4pZ1yageL4TVDDpTTSsv8mK6YaH"
        },
        "feePayer": {
          "feePayer": "B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg",
          "fee": "1",
          "nonce": "1",
          "memo": "",
          "validUntil": "200"
        }
      }
    }
  }
};
