name: Release pkg-pr version
description: Release a new version of o1js and mina-signer using pkg-pr-new

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Restore repository
      uses: actions/cache@v4
      with:
        path: .
        key: repo-${{ github.sha }}
    - name: Setup Node.JS 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: build
      uses: ./.github/actions/build
    - name: Build o1js and mina-signer
      shell: bash
      run: |
        npm ci
        npm run prepublishOnly
        cd src/mina-signer
        npm ci
        npm run prepublishOnly
    - name: Publish o1js and mina-signer on pkg-pr-new
      shell: bash
      run: npx pkg-pr-new publish ./ ./src/mina-signer

