#!/bin/sh

# Check if the developer has enabled pre-commit hooks
if ! git config --get husky.optin > /dev/null; then
  echo "⚠️   Husky pre-commit hook skipped. Enable it with: git config husky.optin true"
  exit 0
fi

echo "⚠️   Husky pre-commit hook enabled. Disable it with: git config --unset husky.optin"

# Filter for diffed (excluding deleted) js and ts files, and format them according to oxlint and prettier rules
git diff --cached --name-only --diff-filter=d | grep -E '\.(ts|js)$' | xargs npm run lint:fix
git diff --cached --name-only --diff-filter=d | grep -E '\.(ts|js)$' | xargs npm run format
