# Purpose: We want to build the o1js bindings in CI so that people in the
# community can change them without being scared of breaking things, or
# needing to do the complicated (without nix) build setup.

name: Build precompiled bindings

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix-builds:
    name: build-bindings-ubuntu
    runs-on: [sdk-self-hosted-linux-amd64-build-system]
    steps:
      - name: Set up Nix
        run: echo "PATH=$PATH:/nix/var/nix/profiles/default/bin" >> $GITHUB_ENV
      - name: Disable smudging
        run: echo "GIT_LFS_SKIP_SMUDGE=1" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build npm-deps
        id: build-npm-deps
        run: |
          set -Eeu
          ./pin.sh
          if ! nix build o1js#npm-deps
          then
            echo npmDepsHash out of date
            echo a fix will be pushed to ${{ github.head_ref }}-ci-fix
            echo please run ./use-ci-fix.sh
            exit 1
          fi
      - name: fix npmDepsHash
        if: failure() && steps.build-npm-deps.outcome == 'failure'
        run: |
          set -Eeu
          ./pin.sh
          nix run o1js#update-npm-deps
      - name: Commit changes
        if: failure() && steps.build-npm-deps.outcome == 'failure'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update npmDepsHash"
          file_pattern: 'npmDepsHash'
          branch: ${{ github.head_ref}}-ci-fix
          create_branch: true
      - name: Build the o1js bindings
        id: bindings-build
        run: |
          set -Eeu
          nix run o1js#update-bindings --max-jobs 4
          if ! git diff --name-only --exit-code src/bindings
          then
            echo bindings need to be rebuilt
            echo a fix will be pushed to ${{ github.head_ref }}-ci-fix
            echo please run ./use-ci-fix.sh
            exit 1
          fi
      - name: Commit new bindings
        if: failure() && steps.bindings-build.outcome == 'failure'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "recompile bindings"
          file_pattern: 'src/bindings/*'
          branch: ${{ github.head_ref}}-ci-fix
          create_branch: true
      - name: add build to gc-root if on main
        if: github.ref == 'refs/heads/main'
        run: |
          nix build o1js#o1js-bindings --out-link /home/app/actions-runner/nix-cache/main-bindings-gcroot
