name: Dump Performance Regression Baseline
on:
  workflow_dispatch: {}

permissions:
  contents: write
jobs:
  dump_and_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          submodules: recursive
      - name: build
        uses: ./.github/actions/build
      - name: Performance Regression (dump)
        uses: ./.github/actions/perf-regression
        env:
          TEST_TYPE: Performance Regression
        with:
          mode: dump
