name: Test o1js against lightnet
on:
  push:
    branches:
      - main
      - v3
      - v1
  pull_request:
    branches:
      - main
      - v3
      - v1
  workflow_dispatch: {}

jobs:
  master:
    timeout-minutes: 45
    runs-on: ubuntu-latest
    services:
      mina-local-network:
        image: o1labs/mina-local-network:master-latest-lightnet
        env:
          NETWORK_TYPE: 'single-node'
          PROOF_LEVEL: 'none'
        ports:
          - 3085:3085
          - 5432:5432
          - 8080:8080
          - 8181:8181
          - 8282:8282
        volumes:
          - /tmp:/root/logs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use shared steps for live testing jobs
        uses: ./.github/actions/live-tests-shared
        with:
          mina-branch-name: master
  compatible:
    timeout-minutes: 45
    runs-on: ubuntu-latest
    services:
      mina-local-network:
        image: o1labs/mina-local-network:compatible-latest-lightnet
        env:
          NETWORK_TYPE: 'single-node'
          PROOF_LEVEL: 'none'
        ports:
          - 3085:3085
          - 5432:5432
          - 8080:8080
          - 8181:8181
          - 8282:8282
        volumes:
          - /tmp:/root/logs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use shared steps for live testing jobs
        uses: ./.github/actions/live-tests-shared
        with:
          mina-branch-name: compatible
