name: Test nix builds for macos

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  devshell:
    name: build-dev-shell-macos
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        node: [18, 20]
        os: [macos-latest]
    steps:
      - name: Disable smudging
        run: echo "GIT_LFS_SKIP_SMUDGE=1" >> $GITHUB_ENV
      - uses: cachix/install-nix-action@v18
          with:
            nix_path: nixpkgs=channel:nixos-unstable
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: build devshell
        run: |
          set -Eeu
          ./pin.sh
          nix build o1js#devShells.default
