name: pkg.pr preview release

on:
  pull_request:
    # Run the workflow when labels are added to a PR or when the PR is updated.
    types:
      - opened
      - synchronize
      - labeled
      - reopened

permissions:
  # Allow the workflow to add comments to pull requests when publishing.
  pull-requests: write

jobs:
  Pkg-pr-new:
    # Only run this job when the pull request contains the pkg‑pr‑release label.
    if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'pkg-pr-release')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore repository
        uses: actions/cache@v4
        with:
          path: .
          key: repo-${{ github.sha }}
      - name: Setup Node.JS 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: build
        uses: ./.github/actions/build
      - name: Build o1js and mina-signer
        run: |
          npm run prepublish:full
          cd src/mina-signer
          npm ci
          npm run prepublish:full
      - name: Publish o1js and mina-signer on pkg-pr-new
        run: npx pkg-pr-new publish ./ ./src/mina-signer # Enable `--compact` once published to NPM with `repository` in package.json