name: Build and upload bindings
on:
  push:
    branches:
      - shigoto/build/bindings-remote 
  workflow_dispatch:
  workflow_call:

jobs:
  Upload-bindings:
    name: upload bindings artifact
    runs-on: [sdk-self-hosted-linux-amd64-build-system]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Install git-lfs
        run: |
          if ! command -v git-lfs &>/dev/null; then
            sudo apt-get update && sudo apt-get install -y git-lfs
          fi
          git lfs install
      
          - name: Fetch Mina submodule (with LFS)
          run: |
            git submodule sync --recursive
            git submodule update --init \
              --depth 1 \
              src/mina
            cd src/mina
            git lfs pull

      - name: upload
        uses: ./.github/actions/upload
        with:
          cache_id: ${{ secrets.NIX_CACHE_ID }}
          nar_secret: ${{ secrets.NIX_CACHE_NAR_SECRET }}
          gcp_secret: ${{ secrets.NIX_CACHE_GCP_SECRET }}

