name: Build and upload bindings
on:
  workflow_dispatch:
  workflow_call:

jobs:
  Upload-bindings:
    name: upload bindings artifact
    runs-on: [shared-o1labs]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: upload
        uses: ./.github/actions/upload
        with:
          cache_id: ${{ secrets.NIX_CACHE_ID }}
          nar_secret: ${{ secrets.NIX_CACHE_NAR_SECRET }}
          gcp_secret: ${{ secrets.NIX_CACHE_GCP_SECRET }}

